# SQLite version 3.x
#   gem install sqlite3
#
#  switched to POSTGRES
#  added username, password, host and port
#  to dev and test
#  though may not need it in dev
development:
  adapter: postgresql
  encoding: unicode
  database: oltest1_dev
  pool: 5
  timeout: 5000
  username: postgres
  password: admin
  host: localhost
  port: 5432

# definitely need username and password in test
test:
  adapter: postgresql
  encoding: unicode
  database: oltest1_test
  pool: 5
  timeout: 5000
  username: postgres
  password: admin
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: oltest1_prod
  pool: 5
  timeout: 5000
